version: "3"
services:
  selenium-hub:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    depends_on:
      - test-runner

  html-server:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-hub
    command: ["sh", "-c", "npm run test && docker-compose down"]
