version: "3"
services:
  selenium-hub:
    image: selenium/standalone-chrome:latest
    # image: seleniarm/standalone-chromium:latest - its image for IOS
    ports:
      - "4444:4444"

  html-server:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-hub
      restart: "no" 
