version: "3"
services:
  selenium-hub:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"

  html-server:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
  video-recorder:  # Новий сервіс для запису відео
    image: selenium/video:ffmpeg-4.3.1-20230904  # Використовуйте відповідний образ
    volumes:
      - /tmp/videos:/videos  # Маппінг директорії для зберігання відео
    depends_on:
      - selenium-hub  # Залежність від selenium-hub
    environment:
      FILE_NAME: my_video.mp4  # Опціонально: вказання імені відеофайлу

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-hub
